# Generated by Django 5.0.7 on 2024-07-15 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('venue_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('performer_name', models.CharField(max_length=50)),
                ('performer_description', models.CharField(max_length=500)),
                ('event_dateAndTime', models.CharField(max_length=50)),
                ('event_price', models.IntegerField(max_length=100)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tunr.venue')),
            ],
        ),
    ]
