# Generated by Django 5.0.7 on 2024-07-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo_url',
            field=models.ImageField(default='../images/defaultEvent.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(default='../images/defaultUser.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='venue',
            name='photo_url',
            field=models.ImageField(default='../images/defaultVenue.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_price',
            field=models.IntegerField(),
        ),
    ]
