# Generated by Django 5.0.7 on 2024-07-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0013_alter_user_user_photo_alter_venue_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo_url',
            field=models.CharField(default='../src/assets/defaultEvent.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.CharField(default='../src/assets/defaultUser.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='photo_url',
            field=models.CharField(default='../src/assets/defaultVenue.jpg', max_length=200),
        ),
    ]
