# Generated by Django 5.0.7 on 2024-07-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0003_alter_event_event_price'),
        ('tunr', '0014_alter_event_photo_url_alter_user_user_photo_and_more'),
    ]

    operations = [
    ]
