# Generated by Django 5.0.7 on 2024-07-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0015_merge_20240718_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(related_name='users', to='tunr.event'),
        ),
    ]
