# Generated by Django 5.0.7 on 2024-07-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0015_merge_20240718_1433'),
        ('tunr', '0016_user_events'),
    ]

    operations = [
    ]
